"""GET /market/skills/{role} — hardcoded MVP skill demand data."""

from datetime import date, timedelta
from typing import Literal

from fastapi import APIRouter, Path, Query, Request

from app.api.middleware.rate_limit import limiter
from app.core.logging import get_logger

router = APIRouter(tags=["market"])
logger = get_logger(__name__)

# Hardcoded for MVP (until crawlers populate the DB)
SKILLS_DATA: dict[str, list[dict[str, object]]] = {
    "ai_engineer": [
        {
            "rank": 1,
            "name": "Python",
            "slug": "python",
            "category": "language",
            "frequency_pct": 94.2,
            "job_count": 1168,
            "trend": "stable",
            "change_pct": 1.2,
        },
        {
            "rank": 2,
            "name": "LangChain",
            "slug": "langchain",
            "category": "ai_ml",
            "frequency_pct": 67.8,
            "job_count": 841,
            "trend": "rising",
            "change_pct": 22.4,
        },
        {
            "rank": 3,
            "name": "SQL",
            "slug": "sql",
            "category": "language",
            "frequency_pct": 65.1,
            "job_count": 807,
            "trend": "stable",
            "change_pct": 0.8,
        },
        {
            "rank": 4,
            "name": "FastAPI",
            "slug": "fastapi",
            "category": "framework",
            "frequency_pct": 58.3,
            "job_count": 723,
            "trend": "rising",
            "change_pct": 15.2,
        },
        {
            "rank": 5,
            "name": "Docker",
            "slug": "docker",
            "category": "devops",
            "frequency_pct": 55.7,
            "job_count": 691,
            "trend": "stable",
            "change_pct": 2.1,
        },
        {
            "rank": 6,
            "name": "RAG",
            "slug": "rag",
            "category": "ai_ml",
            "frequency_pct": 51.2,
            "job_count": 635,
            "trend": "rising",
            "change_pct": 31.5,
        },
        {
            "rank": 7,
            "name": "LangGraph",
            "slug": "langgraph",
            "category": "ai_ml",
            "frequency_pct": 44.8,
            "job_count": 556,
            "trend": "rising",
            "change_pct": 42.0,
        },
        {
            "rank": 8,
            "name": "OpenAI API",
            "slug": "openai-api",
            "category": "ai_ml",
            "frequency_pct": 43.1,
            "job_count": 535,
            "trend": "stable",
            "change_pct": 4.3,
        },
        {
            "rank": 9,
            "name": "AWS",
            "slug": "aws",
            "category": "cloud",
            "frequency_pct": 42.6,
            "job_count": 528,
            "trend": "stable",
            "change_pct": 1.9,
        },
        {
            "rank": 10,
            "name": "PostgreSQL",
            "slug": "postgresql",
            "category": "database",
            "frequency_pct": 38.5,
            "job_count": 478,
            "trend": "stable",
            "change_pct": -0.5,
        },
        {
            "rank": 11,
            "name": "Vector Database",
            "slug": "vector-database",
            "category": "database",
            "frequency_pct": 36.2,
            "job_count": 449,
            "trend": "rising",
            "change_pct": 28.7,
        },
        {
            "rank": 12,
            "name": "Embeddings",
            "slug": "embeddings",
            "category": "ai_ml",
            "frequency_pct": 33.8,
            "job_count": 419,
            "trend": "rising",
            "change_pct": 19.4,
        },
        {
            "rank": 13,
            "name": "Prompt Engineering",
            "slug": "prompt-engineering",
            "category": "ai_ml",
            "frequency_pct": 31.5,
            "job_count": 391,
            "trend": "stable",
            "change_pct": 5.2,
        },
        {
            "rank": 14,
            "name": "REST API",
            "slug": "rest-api",
            "category": "backend",
            "frequency_pct": 28.9,
            "job_count": 358,
            "trend": "stable",
            "change_pct": -1.2,
        },
        {
            "rank": 15,
            "name": "Git",
            "slug": "git",
            "category": "devops",
            "frequency_pct": 26.4,
            "job_count": 327,
            "trend": "stable",
            "change_pct": 0.3,
        },
    ],
    "data_engineer": [
        {
            "rank": 1,
            "name": "Python",
            "slug": "python",
            "category": "language",
            "frequency_pct": 96.1,
            "job_count": 1420,
            "trend": "stable",
            "change_pct": 0.8,
        },
        {
            "rank": 2,
            "name": "SQL",
            "slug": "sql",
            "category": "language",
            "frequency_pct": 93.4,
            "job_count": 1382,
            "trend": "stable",
            "change_pct": 1.1,
        },
        {
            "rank": 3,
            "name": "Spark",
            "slug": "spark",
            "category": "framework",
            "frequency_pct": 72.3,
            "job_count": 1069,
            "trend": "stable",
            "change_pct": -2.1,
        },
        {
            "rank": 4,
            "name": "Airflow",
            "slug": "airflow",
            "category": "platform",
            "frequency_pct": 68.5,
            "job_count": 1014,
            "trend": "stable",
            "change_pct": 3.4,
        },
        {
            "rank": 5,
            "name": "dbt",
            "slug": "dbt",
            "category": "platform",
            "frequency_pct": 61.2,
            "job_count": 906,
            "trend": "rising",
            "change_pct": 18.9,
        },
        {
            "rank": 6,
            "name": "AWS",
            "slug": "aws",
            "category": "cloud",
            "frequency_pct": 58.7,
            "job_count": 869,
            "trend": "stable",
            "change_pct": 2.3,
        },
        {
            "rank": 7,
            "name": "Kafka",
            "slug": "kafka",
            "category": "platform",
            "frequency_pct": 47.3,
            "job_count": 700,
            "trend": "stable",
            "change_pct": -1.8,
        },
        {
            "rank": 8,
            "name": "Docker",
            "slug": "docker",
            "category": "devops",
            "frequency_pct": 43.1,
            "job_count": 638,
            "trend": "stable",
            "change_pct": 4.1,
        },
        {
            "rank": 9,
            "name": "PostgreSQL",
            "slug": "postgresql",
            "category": "database",
            "frequency_pct": 38.9,
            "job_count": 576,
            "trend": "stable",
            "change_pct": 1.5,
        },
        {
            "rank": 10,
            "name": "Git",
            "slug": "git",
            "category": "devops",
            "frequency_pct": 35.2,
            "job_count": 521,
            "trend": "stable",
            "change_pct": 0.4,
        },
    ],
    "analytics_engineer": [
        {
            "rank": 1,
            "name": "SQL",
            "slug": "sql",
            "category": "language",
            "frequency_pct": 97.8,
            "job_count": 1089,
            "trend": "stable",
            "change_pct": 0.5,
        },
        {
            "rank": 2,
            "name": "dbt",
            "slug": "dbt",
            "category": "platform",
            "frequency_pct": 82.3,
            "job_count": 917,
            "trend": "rising",
            "change_pct": 24.6,
        },
        {
            "rank": 3,
            "name": "Python",
            "slug": "python",
            "category": "language",
            "frequency_pct": 74.6,
            "job_count": 831,
            "trend": "stable",
            "change_pct": 1.9,
        },
        {
            "rank": 4,
            "name": "BigQuery",
            "slug": "bigquery",
            "category": "database",
            "frequency_pct": 58.1,
            "job_count": 647,
            "trend": "stable",
            "change_pct": 3.2,
        },
        {
            "rank": 5,
            "name": "Looker",
            "slug": "looker",
            "category": "bi",
            "frequency_pct": 51.4,
            "job_count": 573,
            "trend": "stable",
            "change_pct": -1.4,
        },
        {
            "rank": 6,
            "name": "Snowflake",
            "slug": "snowflake",
            "category": "database",
            "frequency_pct": 47.9,
            "job_count": 534,
            "trend": "rising",
            "change_pct": 11.2,
        },
        {
            "rank": 7,
            "name": "Git",
            "slug": "git",
            "category": "devops",
            "frequency_pct": 43.2,
            "job_count": 481,
            "trend": "stable",
            "change_pct": 0.7,
        },
        {
            "rank": 8,
            "name": "Airflow",
            "slug": "airflow",
            "category": "platform",
            "frequency_pct": 38.7,
            "job_count": 431,
            "trend": "stable",
            "change_pct": 2.8,
        },
        {
            "rank": 9,
            "name": "Tableau",
            "slug": "tableau",
            "category": "bi",
            "frequency_pct": 35.1,
            "job_count": 391,
            "trend": "declining",
            "change_pct": -8.3,
        },
    ],
    "ml_engineer": [
        {
            "rank": 1,
            "name": "Python",
            "slug": "python",
            "category": "language",
            "frequency_pct": 97.1,
            "job_count": 1351,
            "trend": "stable",
            "change_pct": 0.9,
        },
        {
            "rank": 2,
            "name": "TensorFlow",
            "slug": "tensorflow",
            "category": "ai_ml",
            "frequency_pct": 71.2,
            "job_count": 991,
            "trend": "stable",
            "change_pct": -1.2,
        },
        {
            "rank": 3,
            "name": "PyTorch",
            "slug": "pytorch",
            "category": "ai_ml",
            "frequency_pct": 68.9,
            "job_count": 959,
            "trend": "rising",
            "change_pct": 9.4,
        },
        {
            "rank": 4,
            "name": "Docker",
            "slug": "docker",
            "category": "devops",
            "frequency_pct": 63.4,
            "job_count": 882,
            "trend": "stable",
            "change_pct": 2.7,
        },
        {
            "rank": 5,
            "name": "Kubernetes",
            "slug": "kubernetes",
            "category": "devops",
            "frequency_pct": 52.1,
            "job_count": 726,
            "trend": "stable",
            "change_pct": 4.1,
        },
        {
            "rank": 6,
            "name": "MLflow",
            "slug": "mlflow",
            "category": "mlops",
            "frequency_pct": 47.8,
            "job_count": 666,
            "trend": "rising",
            "change_pct": 15.3,
        },
        {
            "rank": 7,
            "name": "SQL",
            "slug": "sql",
            "category": "language",
            "frequency_pct": 44.2,
            "job_count": 615,
            "trend": "stable",
            "change_pct": 1.1,
        },
        {
            "rank": 8,
            "name": "AWS",
            "slug": "aws",
            "category": "cloud",
            "frequency_pct": 43.7,
            "job_count": 608,
            "trend": "stable",
            "change_pct": 2.3,
        },
    ],
}


@router.get("/market/skills/{role}")
@limiter.limit("60/minute")
async def get_market_skills(
    request: Request,
    role: Literal[
        "ai_engineer", "data_engineer", "analytics_engineer", "ml_engineer"
    ] = Path(...),
    weeks: int = Query(default=4, ge=1, le=52),
    country: str = Query(default="AR", max_length=2),
    limit: int = Query(default=50, ge=1, le=100),
) -> dict[str, object]:
    today = date.today()
    period_start = today - timedelta(weeks=weeks)

    skills = SKILLS_DATA.get(role, [])[:limit]
    total_jobs = sum(int(s["job_count"]) for s in skills if isinstance(s["job_count"], int))

    logger.info("market_skills_fetched", role=role, country=country, limit=limit)

    return {
        "role": role,
        "country": country,
        "period": f"{period_start}/{today}",
        "total_jobs_analyzed": total_jobs,
        "skills": skills,
    }
